---
title: "mvdf for Developers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mvdf for Developers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mvdf)
```

```{r}
library(dplyr)
tribble(
  ~ Slot, ~ Class, ~ Package, ~ Description, ~ Units, ~ Class, ~ Unique, ~ Not_missing,
  "x", "mvdf_obj", "mvdf", 'Distance of the origin of the object from the origin of the grid system (the central point at 0, 0, 0) in meters in the x direction. Coordinates are assumed to be on a right-handed coordinate system with Z oriented as the natural "vertical" direction.', "meters", "Numeric", FALSE, TRUE,
  "y", "mvdf_obj", "mvdf", 'Distance of the origin of the object from the origin of the grid system (the central point at 0, 0, 0) in meters in the y direction. Coordinates are assumed to be on a right-handed coordinate system with Z oriented as the natural "vertical" direction.', "meters", "Numeric", FALSE, TRUE,
  "z", "mvdf_obj", "mvdf", 'Distance of the origin of the object from the origin of the grid system (the central point at 0, 0, 0) in meters in the z direction. Coordinates are assumed to be on a right-handed coordinate system with Z oriented as the natural "vertical" direction.', "meters", "Numeric", FALSE, TRUE,
  "idx", "mvdf_obj", "mvdf", 'A unique identifier (or "index") for each object to be modeled.', NA, "Character", TRUE, TRUE,
  "diffuse_color", "mvdf_simple_material", "mvdf", "Diffuse color of the material, as an RGBA array of floats scaled from 0-1.", "Character", NA, FALSE, FALSE,
  "metallic", "mvdf_simple_material", "mvdf", "Amount of mirror reflection for raytrace, as a float from 0-1", "Numeric", "Proportion", FALSE, FALSE,
  "roughness", "mvdf_simple_material", "mvdf", "Roughness of the material, as a float from 0-1.", "Numeric", "Proportion", FALSE, FALSE
)
```

